source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import  register_view, UserDetailView, UserChangeView, \
    UserChangePasswordView, UserListView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register', register_view, name='register'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='user_profile'),
    path('profile/edit/<int:pk>/', UserChangeView.as_view(), name='user_edit'),
    path('profile/edit/pass/<int:pk>', UserChangePasswordView.as_view(), name='user_edit_pass'),
    path('users/', UserListView.as_view(), name='users_list')
]

app_name = 'accounts'

source/api/urls.py
from django.urls import include, path
from rest_framework import routers
from api import views
from rest_framework.authtoken.views import obtain_auth_token

router = routers.DefaultRouter()
router.register(r'projects', views.ProjectViewSet)
router.register(r'tasks', views.TaskViewSet)

app_name = 'api'


urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='api_token_auth')
]

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

source/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    about_me = models.TextField(null=True, blank=True, max_length=200, verbose_name='О себе')
    git = models.URLField(verbose_name='Профиль github', null=True, blank=True)

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class Team(models.Model):
    user = models.ForeignKey('auth.User', related_name='team_user', on_delete=models.CASCADE, verbose_name='Пользователь')
    project = models.ForeignKey('webapp.Project', related_name='team_projects', on_delete=models.CASCADE, verbose_name='Проект')
    date_start = models.DateTimeField(verbose_name='Датасоздания')
    date_finish = models.DateTimeField(verbose_name='Дата окончания')

    def __str__(self):
        return '{} | {}'.format(self.user, self.project)

source/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Profile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label='Email', required=True)
    first_name = forms.CharField(max_length=20, label='Name', required=False)
    last_name = forms.CharField(max_length=20, label='Last Name', required=False)

    class Meta(UserCreationForm.Meta):
        fields = ('username', 'email', 'first_name', 'last_name')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
            raise ValidationError('User with this email already exists', code='user_email_exists')
        except User.DoesNotExist:
            return email

    def clean(self):
        super().clean()
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        if not (first_name or last_name):
            raise ValidationError('Name or Last Name cannot be empty', code='name_or_last_name_empty')

        return self.cleaned_data


class UserUpdateForm(forms.ModelForm):
    avatar = forms.ImageField(label='Аватар', required=False)
    birth_date = forms.DateField(label='День рождения', input_formats=['%Y-%m-%d', '%d.%m.%Y'], required=False)
    about_me = forms.CharField(label='О себе', required=False, widget=forms.Textarea)
    git = forms.URLField(label='Профиль github', required=False)

    def get_initial_for_field(self, field, field_name):
        if field_name in self.Meta.profile_fields:
            return getattr(self.instance.profile, field_name)
        return super().get_initial_for_field(field, field_name)

    def save(self, commit=True):
        user = super().save(commit=commit)
        self.save_profile(commit)
        return user

    def save_profile(self, commit=True):
        profile, _ = Profile.objects.get_or_create(user=self.instance)
        for field in self.Meta.profile_fields:
            setattr(profile, field, self.cleaned_data.get(field))

        if not profile.avatar:
            profile.avatar = None

        if commit:
            profile.save()

    def clean_git(self):
        git = self.cleaned_data.get('git')
        url = ['github.com/', 'https://github.com/', '']
        if git in url:
            return git
        else:
            raise ValidationError('Invalid URL git', code='invalid_url_git')

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'avatar', 'birth_date', 'about_me', 'git']
        profile_fields = ['avatar', 'birth_date', 'about_me', 'git']


class PasswordChangeForm(forms.ModelForm):
    old_password = forms.CharField(max_length=100, label='Old Password', required=True,
                               widget=forms.PasswordInput)
    password = forms.CharField(max_length=100, label='New Password', required=True,
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, label='New Password Confirm', required=True,
                                       widget=forms.PasswordInput)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        user = self.instance
        if not user.check_password(old_password):
            raise ValidationError('Invalid password', code='invalid_password')
        return old_password

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data['password']
        password_2 = self.cleaned_data['password_confirm']
        if password_1 != password_2:
            raise ValidationError('Passwords do not match',
                                  code='passwords_do_not_match')
        return self.cleaned_data

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['old_password', 'password', 'password_confirm']

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, ListView

from accounts.forms import UserCreationForm, UserUpdateForm, PasswordChangeForm, SignUpForm


# def login_view(request):
#     context = {}
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             return redirect('index')
#         else:
#             context['has_error'] = True
#     return render(request, 'accounts/login.html', context=context)


# @login_required
# def logout_view(request):
#     logout(request)
#     return redirect('index')
from accounts.models import Profile


def register_view(request):
    if request.method == 'GET':
        form = SignUpForm()
        return render(request, 'register.html', {'form': form})
    elif request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect('index')
        else:
            return render(request, 'register.html', {'form': form})


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_update.html'
    context_object_name = 'user_obj'
    form_class = UserUpdateForm

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:user_profile', kwargs={'pk': self.object.pk})


class UserChangePasswordView(UserChangeView):
    template_name = 'user_change_pass.html'
    form_class = PasswordChangeForm

    def get_success_url(self):
        return reverse('accounts:login')


class UserListView(ListView):
    context_object_name = 'users'
    template_name = 'users_list.html'
    model = User

source/accounts/templates/login.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
         content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Вход</title>
</head>
<body>
<div class="container">
    <h1>Вход</h1>
    <form action="{% url 'accounts:login' %}" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-error">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" name="password" id="password">
        </div>
        <button type="submit">Войти</button>
    </form>
    <p class="text-center"><a href="{% url "index" %}">На главную</a></p>
</div>

</body>
</html>

source/accounts/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <h1>Sign Up</h1>
    <form action="{% url 'accounts:register' %}" method="post" class="text-center">
        {% include 'partial/task_form.html' with button_text='Save' %}
    </form>
{% endblock %}

source/accounts/templates/user_change_pass.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:user_profile' user_obj.pk %}">View</a></li>
        <li><a href="{% url 'accounts:user_edit' user_obj.pk %}">Edit Profile</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Change Password: {{ user_obj.username }} </h1>
    <form action="{% url 'accounts:user_edit_pass' user_obj.pk %}" method="post">
        {% include 'partial/task_form.html' with button_text='Update' %}
    </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:user_edit' user_obj.pk %}">Edit</a></li>
        <li><a href="{% url 'accounts:user_edit_pass' user_obj.pk %}">Change Password</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Profile: {{ user_obj.username }} </h1>
    {% if user_obj.profile.avatar %}
        <img src="{{ user_obj.profile.avatar.url }}" alt="user_pic" class="avatar">
    {% else %}
        <img src="{% static 'img/images.png' %}" alt="user_pic" class="avatar">
    {% endif %}
    <p>First Name: {{ user_obj.first_name }}</p>
    <p>Last  Name: {{ user_obj.last_name }}</p>
    <p>Email: {{ user_obj.email }}</p>
    <p>Birth Day: {{ user_obj.profile.birth_date|date:"d:m:Y" }}</p>
    <p>About me: {{ user_obj.profile.about_me }}</p>
    <p>Git: {{ user_obj.profile.git }}</p>

{% endblock %}

source/accounts/templates/user_update.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:user_profile' user_obj.pk %}">View</a></li>
        <li><a href="{% url 'accounts:user_edit_pass' user_obj.pk %}">Change Password</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Profile: {{ user_obj.username }} </h1>
    <form action="{% url 'accounts:user_edit' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% include 'partial/task_form.html' with button_text='Update' %}
    </form>
{% endblock %}

source/accounts/templates/users_list.html
{% extends 'base.html' %}

{% block menu %}
{#           <li><a href="{% url 'project_create' %} ">Add Project</a></li>#}

{% endblock %}
{% block content %}
<h1 class="text-center">Users:</h1>
{#    {% if request.user.is_authenticated %}#}
{#    {% endif %}#}
    {% for user in users %}
        <h2>{{ user.username }}</h2>
        <p><a href="{% url 'accounts:user_profile' user.pk %}">Personal Account</a></p>
        <hr/>
    {% endfor %}
{% endblock %}
</body>
</html>